
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always

  backend:
    build: .
    container_name: app
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - redis
    ports:
      - "8000:8000"

  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    env_file:
      - .env.prod
    depends_on:
      - redis
    command: celery -A src.celery_app worker -l info

  flower:
    image: mher/flower
    container_name: flower
    restart: always
    depends_on:
      - redis
      - celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "5555:5555"
